# Site settings
title: Lucky
description: Lucky Blog. This is your RSS. Welcome!

baseurl: /blog # the subpath of your site, e.g. /blog/
abouturl: lucky521.github.io
url: lucky521.github.io/blog # the base hostname & protocol for your site

author:
  fullname: Lucky
  github: lucky521
  disqus: yes

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
#markdown: kramdown
#markdown: redcarpet